In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
import nltk

In [2]:
books=pd.read_csv('Goodreadss Books.csv')
books

,Unnamed: 0,bookId,title,author,series,description,genres,awards,characters,places,...,publish_date,num_pages,num_ratings,num_reviews,avg_rating,rated_1,rated_2,rated_3,rated_4,rated_5
0,0,1,Harry Potter and the Half-Blood Prince,J.K. Rowling,Harry Potter #6,The war against Voldemort is not going well; e...,"Art,Biography,Business,Children's,Christian,Cl...",Locus Award Nominee for Best Young Adult Novel...,"Draco Malfoy,Ron Weasley,Petunia Dursley,Verno...","Hogwarts School of Witchcraft and Wizardry,Eng...",...,September 16th 2006,652.0,2553909.0,41470.0,4.57,13147.0,29020.0,174312.0,608825.0,1728605.0
1,1,2,Harry Potter and the Order of the Phoenix,"J.K. Rowling,Mary GrandPré",Harry Potter #5,There is a door at the end of a silent corrido...,"Art,Biography,Business,Children's,Christian,Cl...",Bram Stoker Award for Works for Young Readers ...,"Sirius Black,Draco Malfoy,Ron Weasley,Petunia ...","Hogwarts School of Witchcraft and Wizardry,Lon...",...,September 2004,870.0,2631427.0,44793.0,4.50,16236.0,41738.0,231438.0,665628.0,1676387.0
2,2,3,Harry Potter and the Sorcerer's Stone,"J.K. Rowling,Mary GrandPré",Harry Potter #1,Harry Potter's life is miserable. His parents ...,"Art,Biography,Business,Children's,Christian,Cl...",Mythopoeic Fantasy Award for Children's Litera...,"Draco Malfoy,Ron Weasley,Petunia Dursley,Verno...","London, England,Hogwarts School of Witchcraft ...",...,November 1st 2003,309.0,7434783.0,117823.0,4.48,126344.0,147184.0,627803.0,1694206.0,4839246.0
3,3,4,Harry Potter and the Chamber of Secrets,J.K. Rowling,Harry Potter #2,The Dursleys were so mean and hideous that sum...,"Art,Biography,Business,Children's,Christian,Cl...",Mythopoeic Fantasy Award for Children's Litera...,"Draco Malfoy,Ron Weasley,Petunia Dursley,Verno...","Hogwarts School of Witchcraft and Wizardry,Hog...",...,November 1st 2003,352.0,2878196.0,55839.0,4.43,15623.0,55060.0,315917.0,787181.0,1704415.0
4,4,5,Harry Potter and the Prisoner of Azkaban,"J.K. Rowling,Mary GrandPré",Harry Potter #3,"For twelve long years, the dread fortress of A...","Art,Biography,Business,Children's,Christian,Cl...",Bram Stoker Award for Best Work for Young Read...,"Sirius Black,Draco Malfoy,Ron Weasley,Petunia ...","Hogwarts School of Witchcraft and Wizardry,Lon...",...,May 1st 2004,435.0,2972519.0,58483.0,4.57,14124.0,29105.0,214151.0,701765.0,2013374.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20063,20063,19996,Connecticut: In Words and Pictures,"Dennis Brindell Fradin,Richard Wahl,Len W. Meents",NaN,"A brief introduction to the history, geography...","Art,Biography,Business,Children's,Christian,Cl...",NaN,NaN,NaN,...,March 1st 1980,48.0,0.0,0.0,0.00,NaN,NaN,NaN,NaN,NaN
20064,20064,19997,Through a Brazen Mirror,"Delia Sherman,Cortney Skinner,Ellen Kushner",NaN,In a medieval kingdom both like and unlike 13t...,"Art,Biography,Business,Children's,Christian,Cl...",NaN,NaN,NaN,...,February 25th 2015,100.0,141.0,16.0,3.38,8.0,15.0,52.0,47.0,19.0
20065,20065,19998,The Porcelain Dove,Delia Sherman,NaN,Narrated by the irrepressible chambermaid to a...,"Art,Biography,Business,Children's,Christian,Cl...",Mythopoeic Fantasy Award for Adult Literature ...,NaN,NaN,...,July 1st 1994,416.0,242.0,36.0,3.41,18.0,35.0,72.0,63.0,54.0
20066,20066,19999,The Fall Of The Kings,"Ellen Kushner,Delia Sherman",The World of Riverside #3,"From School Library Journal,Adult/High School-...","Art,Biography,Business,Children's,Christian,Cl...",World Fantasy Award Nominee for Best Novella 1...,NaN,NaN,...,2002,NaN,2153.0,167.0,3.65,61.0,214.0,640.0,734.0,504.0
20067,20067,20000,Die Blume der Diener,"Delia Sherman,Michael Siefener",NaN,Der junge William Flower kommt als Unbekannter...,"Art,Biography,Business,Children's,Christian,Cl...",NaN,NaN,NaN,...,2001,318.0,141.0,16.0,3.38,8.0,15.0,52.0,47.0,19.0

In [3]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20068 entries, 0 to 20067
Data columns (total 24 columns):
Unnamed: 0            20068 non-null int64
bookId                20068 non-null int64
title                 19509 non-null object
author                19507 non-null object
series                4279 non-null object
description           17381 non-null object
genres                19812 non-null object
awards                3129 non-null object
characters            4779 non-null object
places                4040 non-null object
isbn                  17531 non-null object
isbn13                19210 non-null object
language              17289 non-null object
first_publish_date    14591 non-null object
publish_date          19022 non-null object
num_pages             18428 non-null float64
num_ratings           19509 non-null float64
num_reviews           19509 non-null float64
avg_rating            19509 non-null float64
rated_1               16638 non-null float64
rated_2               16638 non-null float64
rated_3               16638 non-null float64
rated_4               16638 non-null float64
rated_5               16638 non-null float64
dtypes: float64(9), int64(2), object(13)
memory usage: 3.7+ MB

In [4]:
books.columns

Index(['Unnamed: 0', 'bookId', 'title', 'author', 'series', 'description',
       'genres', 'awards', 'characters', 'places', 'isbn', 'isbn13',
       'language', 'first_publish_date', 'publish_date', 'num_pages',
       'num_ratings', 'num_reviews', 'avg_rating', 'rated_1', 'rated_2',
       'rated_3', 'rated_4', 'rated_5'],
      dtype='object')

In [5]:
books['author']

0                                             J.K. Rowling
1                               J.K. Rowling,Mary GrandPré
2                               J.K. Rowling,Mary GrandPré
3                                             J.K. Rowling
4                               J.K. Rowling,Mary GrandPré
                               ...
20063    Dennis Brindell Fradin,Richard Wahl,Len W. Meents
20064          Delia Sherman,Cortney Skinner,Ellen Kushner
20065                                        Delia Sherman
20066                          Ellen Kushner,Delia Sherman
20067                       Delia Sherman,Michael Siefener
Name: author, Length: 20068, dtype: object

In [6]:
books['genres'][0]

"Art,Biography,Business,Children's,Christian,Classics,Comics,Cookbooks,Ebooks,Fantasy,Fiction,Graphic Novels,Historical Fiction,History,Horror,Memoir,Music,Mystery,Nonfiction,Poetry,Psychology,Romance,Science,Science Fiction,Self Help,Sports,Thriller,Travel,Young Adult,Art,Biography,Business,Children's,Christian,Classics,Comics,Cookbooks,Ebooks,Fantasy,Fiction,Graphic Novels,Historical Fiction,History,Horror,Memoir,Music,Mystery,Nonfiction,Poetry,Psychology,Romance,Science,Science Fiction,Self Help,Sports,Thriller,Travel,Young Adult,Fantasy,Young Adult,Fiction,Fantasy,Magic,Childrens,Adventure,Audiobook,Childrens,Middle Grade,Classics,Science Fiction Fantasy"

In [7]:
books['genres'][1]

"Art,Biography,Business,Children's,Christian,Classics,Comics,Cookbooks,Ebooks,Fantasy,Fiction,Graphic Novels,Historical Fiction,History,Horror,Memoir,Music,Mystery,Nonfiction,Poetry,Psychology,Romance,Science,Science Fiction,Self Help,Sports,Thriller,Travel,Young Adult,Art,Biography,Business,Children's,Christian,Classics,Comics,Cookbooks,Ebooks,Fantasy,Fiction,Graphic Novels,Historical Fiction,History,Horror,Memoir,Music,Mystery,Nonfiction,Poetry,Psychology,Romance,Science,Science Fiction,Self Help,Sports,Thriller,Travel,Young Adult,Fantasy,Young Adult,Fiction,Fantasy,Magic,Childrens,Adventure,Audiobook,Childrens,Middle Grade,Classics,Science Fiction Fantasy"

In [8]:
books['genres']

0        Art,Biography,Business,Children's,Christian,Cl...
1        Art,Biography,Business,Children's,Christian,Cl...
2        Art,Biography,Business,Children's,Christian,Cl...
3        Art,Biography,Business,Children's,Christian,Cl...
4        Art,Biography,Business,Children's,Christian,Cl...
                               ...
20063    Art,Biography,Business,Children's,Christian,Cl...
20064    Art,Biography,Business,Children's,Christian,Cl...
20065    Art,Biography,Business,Children's,Christian,Cl...
20066    Art,Biography,Business,Children's,Christian,Cl...
20067    Art,Biography,Business,Children's,Christian,Cl...
Name: genres, Length: 20068, dtype: object

In [9]:
books.isnull().sum()/len(books)*100

Unnamed: 0             0.000000
bookId                 0.000000
title                  2.785529
author                 2.795495
series                78.677497
description           13.389476
genres                 1.275663
awards                84.408013
characters            76.185968
places                79.868447
isbn                  12.642017
isbn13                 4.275463
language              13.847917
first_publish_date    27.292206
publish_date           5.212278
num_pages              8.172214
num_ratings            2.785529
num_reviews            2.785529
avg_rating             2.785529
rated_1               17.091888
rated_2               17.091888
rated_3               17.091888
rated_4               17.091888
rated_5               17.091888
dtype: float64

In [10]:
books=books.drop(['Unnamed: 0'],axis=1)

In [11]:
books['awards'][3]

"Mythopoeic Fantasy Award for Children's Literature 2008,British Book Award 1999,Prijs van de Jonge Jury 2002,Books I Loved Best Yearly BILBY Awards for Older Readers 2006,Colorado Blue Spruce Young Adult Book Award 2008,Golden Archer Award for Middle/Junior High 2008,Nestlé Smarties Book Prize for 9–11 years 1998"

In [12]:
#books['series'].head(20)

In [13]:
#books[['isbn','isbn13']]

In [14]:
books.head(100)['language'].unique()

array(['English', nan, 'Spanish', 'French'], dtype=object)

In [15]:
books['language'].value_counts()/len(books)*100

English                      81.328483
Spanish                       2.237393
German                        0.971696
French                        0.847120
Japanese                      0.234204
Multiple languages            0.119593
Italian                       0.069763
Chinese                       0.069763
Portuguese                    0.064780
Greek, Ancient to 1453        0.049831
Russian                       0.044848
Arabic                        0.019932
Latin                         0.019932
Dutch                         0.014949
Turkish                       0.009966
Greek, Modern 1453-           0.009966
English, Middle 1100-1500     0.009966
Danish                        0.009966
Serbian                       0.004983
Norwegian                     0.004983
Ladino                        0.004983
Munda languages               0.004983
Name: language, dtype: float64

In [16]:
books = books.drop(['series','description','awards','characters','places','isbn','isbn13','language','first_publish_date','publish_date','num_pages'],axis=1)

In [25]:
#books[books.duplicated()]

In [26]:
#books[books.duplicated(keep=False)]

In [19]:
books['bookId'].is_unique

False

In [20]:
books1 = books.drop_duplicates()
books1

,bookId,title,author,genres,num_ratings,num_reviews,avg_rating,rated_1,rated_2,rated_3,rated_4,rated_5
0,1,Harry Potter and the Half-Blood Prince,J.K. Rowling,"Art,Biography,Business,Children's,Christian,Cl...",2553909.0,41470.0,4.57,13147.0,29020.0,174312.0,608825.0,1728605.0
1,2,Harry Potter and the Order of the Phoenix,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...",2631427.0,44793.0,4.50,16236.0,41738.0,231438.0,665628.0,1676387.0
2,3,Harry Potter and the Sorcerer's Stone,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...",7434783.0,117823.0,4.48,126344.0,147184.0,627803.0,1694206.0,4839246.0
3,4,Harry Potter and the Chamber of Secrets,J.K. Rowling,"Art,Biography,Business,Children's,Christian,Cl...",2878196.0,55839.0,4.43,15623.0,55060.0,315917.0,787181.0,1704415.0
4,5,Harry Potter and the Prisoner of Azkaban,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...",2972519.0,58483.0,4.57,14124.0,29105.0,214151.0,701765.0,2013374.0
...,...,...,...,...,...,...,...,...,...,...,...,...
20063,19996,Connecticut: In Words and Pictures,"Dennis Brindell Fradin,Richard Wahl,Len W. Meents","Art,Biography,Business,Children's,Christian,Cl...",0.0,0.0,0.00,NaN,NaN,NaN,NaN,NaN
20064,19997,Through a Brazen Mirror,"Delia Sherman,Cortney Skinner,Ellen Kushner","Art,Biography,Business,Children's,Christian,Cl...",141.0,16.0,3.38,8.0,15.0,52.0,47.0,19.0
20065,19998,The Porcelain Dove,Delia Sherman,"Art,Biography,Business,Children's,Christian,Cl...",242.0,36.0,3.41,18.0,35.0,72.0,63.0,54.0
20066,19999,The Fall Of The Kings,"Ellen Kushner,Delia Sherman","Art,Biography,Business,Children's,Christian,Cl...",2153.0,167.0,3.65,61.0,214.0,640.0,734.0,504.0
20067,20000,Die Blume der Diener,"Delia Sherman,Michael Siefener","Art,Biography,Business,Children's,Christian,Cl...",141.0,16.0,3.38,8.0,15.0,52.0,47.0,19.0

In [21]:
books1.duplicated().sum()

0

In [24]:
books1['bookId'].is_unique

False

In [23]:
books.duplicated().sum()

123

In [28]:
books1.isnull().sum()

bookId            0
title           558
author          560
genres          256
num_ratings     558
num_reviews     558
avg_rating      558
rated_1        3408
rated_2        3408
rated_3        3408
rated_4        3408
rated_5        3408
dtype: int64

In [29]:
books1.iloc[0].genres

"Art,Biography,Business,Children's,Christian,Classics,Comics,Cookbooks,Ebooks,Fantasy,Fiction,Graphic Novels,Historical Fiction,History,Horror,Memoir,Music,Mystery,Nonfiction,Poetry,Psychology,Romance,Science,Science Fiction,Self Help,Sports,Thriller,Travel,Young Adult,Art,Biography,Business,Children's,Christian,Classics,Comics,Cookbooks,Ebooks,Fantasy,Fiction,Graphic Novels,Historical Fiction,History,Horror,Memoir,Music,Mystery,Nonfiction,Poetry,Psychology,Romance,Science,Science Fiction,Self Help,Sports,Thriller,Travel,Young Adult,Fantasy,Young Adult,Fiction,Fantasy,Magic,Childrens,Adventure,Audiobook,Childrens,Middle Grade,Classics,Science Fiction Fantasy"

In [30]:
books1 = books1.drop(['rated_1','rated_2','rated_3','rated_4','rated_5'],axis=1)

In [31]:
books1

,bookId,title,author,genres,num_ratings,num_reviews,avg_rating
0,1,Harry Potter and the Half-Blood Prince,J.K. Rowling,"Art,Biography,Business,Children's,Christian,Cl...",2553909.0,41470.0,4.57
1,2,Harry Potter and the Order of the Phoenix,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...",2631427.0,44793.0,4.50
2,3,Harry Potter and the Sorcerer's Stone,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...",7434783.0,117823.0,4.48
3,4,Harry Potter and the Chamber of Secrets,J.K. Rowling,"Art,Biography,Business,Children's,Christian,Cl...",2878196.0,55839.0,4.43
4,5,Harry Potter and the Prisoner of Azkaban,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...",2972519.0,58483.0,4.57
...,...,...,...,...,...,...,...
20063,19996,Connecticut: In Words and Pictures,"Dennis Brindell Fradin,Richard Wahl,Len W. Meents","Art,Biography,Business,Children's,Christian,Cl...",0.0,0.0,0.00
20064,19997,Through a Brazen Mirror,"Delia Sherman,Cortney Skinner,Ellen Kushner","Art,Biography,Business,Children's,Christian,Cl...",141.0,16.0,3.38
20065,19998,The Porcelain Dove,Delia Sherman,"Art,Biography,Business,Children's,Christian,Cl...",242.0,36.0,3.41
20066,19999,The Fall Of The Kings,"Ellen Kushner,Delia Sherman","Art,Biography,Business,Children's,Christian,Cl...",2153.0,167.0,3.65
20067,20000,Die Blume der Diener,"Delia Sherman,Michael Siefener","Art,Biography,Business,Children's,Christian,Cl...",141.0,16.0,3.38

In [32]:
books1 = books1.dropna(axis=0,subset= ['title'])

In [33]:
books1.isnull().sum()

bookId         0
title          0
author         2
genres         0
num_ratings    0
num_reviews    0
avg_rating     0
dtype: int64

In [34]:
books1.shape

(19387, 7)

In [35]:
books1 = books1.dropna()

In [36]:
books1.isnull().sum()

bookId         0
title          0
author         0
genres         0
num_ratings    0
num_reviews    0
avg_rating     0
dtype: int64

In [37]:
books2 = books1[['bookId','title','author','genres']]

In [38]:
books2

,bookId,title,author,genres
0,1,Harry Potter and the Half-Blood Prince,J.K. Rowling,"Art,Biography,Business,Children's,Christian,Cl..."
1,2,Harry Potter and the Order of the Phoenix,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl..."
2,3,Harry Potter and the Sorcerer's Stone,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl..."
3,4,Harry Potter and the Chamber of Secrets,J.K. Rowling,"Art,Biography,Business,Children's,Christian,Cl..."
4,5,Harry Potter and the Prisoner of Azkaban,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl..."
...,...,...,...,...
20063,19996,Connecticut: In Words and Pictures,"Dennis Brindell Fradin,Richard Wahl,Len W. Meents","Art,Biography,Business,Children's,Christian,Cl..."
20064,19997,Through a Brazen Mirror,"Delia Sherman,Cortney Skinner,Ellen Kushner","Art,Biography,Business,Children's,Christian,Cl..."
20065,19998,The Porcelain Dove,Delia Sherman,"Art,Biography,Business,Children's,Christian,Cl..."
20066,19999,The Fall Of The Kings,"Ellen Kushner,Delia Sherman","Art,Biography,Business,Children's,Christian,Cl..."
20067,20000,Die Blume der Diener,"Delia Sherman,Michael Siefener","Art,Biography,Business,Children's,Christian,Cl..."

In [39]:
books2['tags'] = books2['author']+books2['genres']
books2

C:\Users\harin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,bookId,title,author,genres,tags
0,1,Harry Potter and the Half-Blood Prince,J.K. Rowling,"Art,Biography,Business,Children's,Christian,Cl...","J.K. RowlingArt,Biography,Business,Children's,..."
1,2,Harry Potter and the Order of the Phoenix,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...","J.K. Rowling,Mary GrandPréArt,Biography,Busine..."
2,3,Harry Potter and the Sorcerer's Stone,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...","J.K. Rowling,Mary GrandPréArt,Biography,Busine..."
3,4,Harry Potter and the Chamber of Secrets,J.K. Rowling,"Art,Biography,Business,Children's,Christian,Cl...","J.K. RowlingArt,Biography,Business,Children's,..."
4,5,Harry Potter and the Prisoner of Azkaban,"J.K. Rowling,Mary GrandPré","Art,Biography,Business,Children's,Christian,Cl...","J.K. Rowling,Mary GrandPréArt,Biography,Busine..."
...,...,...,...,...,...
20063,19996,Connecticut: In Words and Pictures,"Dennis Brindell Fradin,Richard Wahl,Len W. Meents","Art,Biography,Business,Children's,Christian,Cl...","Dennis Brindell Fradin,Richard Wahl,Len W. Mee..."
20064,19997,Through a Brazen Mirror,"Delia Sherman,Cortney Skinner,Ellen Kushner","Art,Biography,Business,Children's,Christian,Cl...","Delia Sherman,Cortney Skinner,Ellen KushnerArt..."
20065,19998,The Porcelain Dove,Delia Sherman,"Art,Biography,Business,Children's,Christian,Cl...","Delia ShermanArt,Biography,Business,Children's..."
20066,19999,The Fall Of The Kings,"Ellen Kushner,Delia Sherman","Art,Biography,Business,Children's,Christian,Cl...","Ellen Kushner,Delia ShermanArt,Biography,Busin..."
20067,20000,Die Blume der Diener,"Delia Sherman,Michael Siefener","Art,Biography,Business,Children's,Christian,Cl...","Delia Sherman,Michael SiefenerArt,Biography,Bu..."

In [40]:
books3 = books2[['bookId','title','tags']]
books3

,bookId,title,tags
0,1,Harry Potter and the Half-Blood Prince,"J.K. RowlingArt,Biography,Business,Children's,..."
1,2,Harry Potter and the Order of the Phoenix,"J.K. Rowling,Mary GrandPréArt,Biography,Busine..."
2,3,Harry Potter and the Sorcerer's Stone,"J.K. Rowling,Mary GrandPréArt,Biography,Busine..."
3,4,Harry Potter and the Chamber of Secrets,"J.K. RowlingArt,Biography,Business,Children's,..."
4,5,Harry Potter and the Prisoner of Azkaban,"J.K. Rowling,Mary GrandPréArt,Biography,Busine..."
...,...,...,...
20063,19996,Connecticut: In Words and Pictures,"Dennis Brindell Fradin,Richard Wahl,Len W. Mee..."
20064,19997,Through a Brazen Mirror,"Delia Sherman,Cortney Skinner,Ellen KushnerArt..."
20065,19998,The Porcelain Dove,"Delia ShermanArt,Biography,Business,Children's..."
20066,19999,The Fall Of The Kings,"Ellen Kushner,Delia ShermanArt,Biography,Busin..."
20067,20000,Die Blume der Diener,"Delia Sherman,Michael SiefenerArt,Biography,Bu..."

In [41]:
books3['tags'] = books3['tags'].apply(lambda x: x.lower())

C:\Users\harin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [42]:
books3

,bookId,title,tags
0,1,Harry Potter and the Half-Blood Prince,"j.k. rowlingart,biography,business,children's,..."
1,2,Harry Potter and the Order of the Phoenix,"j.k. rowling,mary grandpréart,biography,busine..."
2,3,Harry Potter and the Sorcerer's Stone,"j.k. rowling,mary grandpréart,biography,busine..."
3,4,Harry Potter and the Chamber of Secrets,"j.k. rowlingart,biography,business,children's,..."
4,5,Harry Potter and the Prisoner of Azkaban,"j.k. rowling,mary grandpréart,biography,busine..."
...,...,...,...
20063,19996,Connecticut: In Words and Pictures,"dennis brindell fradin,richard wahl,len w. mee..."
20064,19997,Through a Brazen Mirror,"delia sherman,cortney skinner,ellen kushnerart..."
20065,19998,The Porcelain Dove,"delia shermanart,biography,business,children's..."
20066,19999,The Fall Of The Kings,"ellen kushner,delia shermanart,biography,busin..."
20067,20000,Die Blume der Diener,"delia sherman,michael siefenerart,biography,bu..."

In [35]:
#books3['tags'] = books3['tags'].apply(lambda x: x.split())

In [36]:
#books3['tags'] = books3['tags'].apply(lambda x: [i.replace(","," ") for i in x])

In [37]:
#books2['tags'] = books3['tags'].apply(lambda x: " ".join(x))[0]

In [38]:
#!pip install nltk

In [43]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [44]:
def stem(text):
    y = []
    for i in  text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [45]:
#ps.stem('dance')

In [46]:
books3['tags'][0]

"j.k. rowlingart,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graphic novels,historical fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,science fiction,self help,sports,thriller,travel,young adult,fantasy,young adult,fiction,fantasy,magic,childrens,adventure,audiobook,childrens,middle grade,classics,science fiction fantasy"

In [47]:
stem("j.k. rowlingart biography business children's christian classics comics cookbooks ebooks fantasy fiction graphic novels historical fiction history horror memoir music mystery nonfiction poetry psychology romance science science fiction self help sports thriller travel young adult art biography business children's christian classics comics cookbooks ebooks fantasy fiction graphic novels historical fiction history horror memoir music mystery nonfiction poetry psychology romance science science fiction self help sports thriller travel young adult fantasy young adult fiction fantasy magic childrens adventure audiobook childrens middle grade classics science fiction fantasy")

"j.k. rowlingart biographi busi children' christian classic comic cookbook ebook fantasi fiction graphic novel histor fiction histori horror memoir music mysteri nonfict poetri psycholog romanc scienc scienc fiction self help sport thriller travel young adult art biographi busi children' christian classic comic cookbook ebook fantasi fiction graphic novel histor fiction histori horror memoir music mysteri nonfict poetri psycholog romanc scienc scienc fiction self help sport thriller travel young adult fantasi young adult fiction fantasi magic children adventur audiobook children middl grade classic scienc fiction fantasi"

In [48]:
#stem('comicbooks')

In [49]:
books3['tags'] = books3['tags'].apply(stem)

C:\Users\harin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [52]:
vectors = cv.fit_transform(books3['tags']).toarray()

In [53]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [54]:
cv.get_feature_names() #our corpus words

['13th',
 '14th',
 '16th',
 '17th',
 '182art',
 '18th',
 '19th',
 '1st',
 '20th',
 '21st',
 '2nd',
 '40k',
 'aardman',
 'aaron',
 'abadiaart',
 'abanesart',
 'abbi',
 'abbott',
 'abbottart',
 'abdel',
 'abe',
 'abelart',
 'abigail',
 'abraham',
 'abrahamart',
 'abrahamsart',
 'abu',
 'abus',
 'abuse',
 'academ',
 'academi',
 'academia',
 'academic',
 'academics',
 'achebe',
 'achebeart',
 'achil',
 'acker',
 'ackerart',
 'ackermanart',
 'acresart',
 'act',
 'action',
 'activ',
 'activism',
 'aczelart',
 'ada',
 'adam',
 'adamart',
 'adamo',
 'adams',
 'adamsart',
 'addison',
 'adela',
 'adelman',
 'adi',
 'adkinsart',
 'adlerart',
 'adolescence',
 'adolph',
 'adopt',
 'adoption',
 'adrian',
 'adriana',
 'adrienn',
 'adrián',
 'adult',
 'adventur',
 'adventure',
 'adèl',
 'aeschylus',
 'africa',
 'african',
 'aftelart',
 'agassiz',
 'agatha',
 'age',
 'ageeart',
 'aglaia',
 'agn',
 'agriculture',
 'agustín',
 'agutterart',
 'ahern',
 'ahernart',
 'ai',
 'aigner',
 'aime',
 'aio',
 'aitkenart',
 'akira',
 'al',
 'alain',
 'alan',
 'alastair',
 'albanian',
 'albert',
 'alberto',
 'alberts',
 'albomart',
 'alcohol',
 'alcornart',
 'alcott',
 'alcottart',
 'alden',
 'aldou',
 'alec',
 'alejandro',
 'alex',
 'alexand',
 'alexander',
 'alexanderart',
 'alexandr',
 'alexandra',
 'alexi',
 'alfonso',
 'alfr',
 'algeria',
 'ali',
 'aliart',
 'alic',
 'alien',
 'aliens',
 'alighieri',
 'alighieriart',
 'alison',
 'alistair',
 'allan',
 'allanart',
 'allen',
 'allenart',
 'allende',
 'allendeart',
 'allender',
 'allenderart',
 'alleyart',
 'allison',
 'allisonart',
 'alma',
 'altern',
 'alton',
 'alvarez',
 'alvarezart',
 'alvin',
 'alyssa',
 'amanda',
 'amano',
 'amartya',
 'amazon',
 'ambrus',
 'america',
 'americaart',
 'american',
 'americana',
 'americans',
 'ames',
 'ami',
 'amielart',
 'amin',
 'amir',
 'amisart',
 'amish',
 'amitabha',
 'amori',
 'amour',
 'amourart',
 'améli',
 'ana',
 'anagnostou',
 'anak',
 'anatol',
 'anayaart',
 'anaï',
 'anci',
 'ancient',
 'andersen',
 'andersenart',
 'anderson',
 'andersonart',
 'andi',
 'andr',
 'andrea',
 'andrei',
 'andrew',
 'andrewart',
 'andrewesart',
 'andrewsart',
 'andrić',
 'andrićart',
 'andré',
 'angel',
 'angela',
 'angelica',
 'angellart',
 'angelo',
 'angelou',
 'angelouart',
 'angels',
 'angi',
 'angu',
 'angus',
 'angusart',
 'anim',
 'animals',
 'anime',
 'animo',
 'anita',
 'anjali',
 'anker',
 'ann',
 'anna',
 'annabel',
 'anne',
 'annett',
 'anni',
 'anonymous',
 'anonymousart',
 'anouilhart',
 'anscombeart',
 'anthea',
 'antholog',
 'anthologies',
 'anthoni',
 'anthony',
 'anthonyart',
 'anthropolog',
 'anthropology',
 'anti',
 'antoin',
 'antolín',
 'anton',
 'antoni',
 'antonia',
 'antonio',
 'antrimart',
 'apocalypt',
 'apocalyptic',
 'appalachian',
 'appelart',
 'appelbaumart',
 'appignanesiart',
 'apthekerart',
 'arakawa',
 'araki',
 'arakiart',
 'arana',
 'archaeolog',
 'archaeology',
 'archerart',
 'archibald',
 'architectur',
 'architecture',
 'arci',
 'arco',
 'arden',
 'ariel',
 'ariewart',
 'aristophanes',
 'aristophanesart',
 'aristotle',
 'aristotleart',
 'arkangel',
 'arlen',
 'armestoart',
 'armin',
 'armistead',
 'armstrong',
 'armstrongart',
 'arn',
 'arnettart',
 'arnim',
 'arnimart',
 'arnold',
 'arnoldart',
 'arrow',
 'arrowart',
 'arrowsmith',
 'arrowsmithart',
 'arsdale',
 'art',
 'arthur',
 'arthurart',
 'arthurian',
 'artifici',
 'arts',
 'arturo',
 'arundhati',
 'ashley',
 'asia',
 'asian',
 'associ',
 'association',
 'associationart',
 'astrid',
 'astronomi',
 'astronomy',
 'ath',
 'atheism',
 'attack',
 'atwoodart',
 'aubrey',
 'audiobook',
 'audrey',
 'auelart',
 'auer',
 'august',
 'augusten',
 'augustin',
 'austen',
 'austenart',
 'auster',
 'austerart',
 'australia',
 'author',
 'authors',
 'autobiographi',
 'autobiography',
 'avery',
 'averyart',
 'avi',
 'aviart',
 'aviation',
 'award',
 'awards',
 'axlerart',
 'aylm',
 'ayn',
 'azar',
 'babbitt',
 'babbittart',
 'bachart',
 'bachelder',
 'bachelderart',
 'bachman',
 'bader',
 'baderart',
 'baerart',
 'bai',
 'bailey',
 'baileyart',
 'bairart',
 'bajwaart',
 'baker',
 'bakerart',
 'bakewell',
 'bakkerart',
 'baldacci',
 'baldacciart',
 'baldwin',
 'baldwinart',
 'ballart',
 'ballet',
 'ban',
 'band',
 'bank',
 'banking',
 'banks',
 'banksart',
 'banvilleart',
 'barbara',
 'barberart',
 'bardes',
 'barker',
 'barkerart',
 'barks',
 'barksart',
 'barnardart',
 'barnes',
 'barnesart',
 'barnett',
 'barnettart',
 'barney',
 'barnicleart',
 'baronova',
 'barrangerart',
 'barresart',
 'barrett',
 'barrettart',
 'barri',
 'barron',
 'barronart',
 'barry',
 'barryart',
 'barsamianart',
 'bart',
 'barthart',
 'bartholomew',
 'bartholomewart',
 'barton',
 'barzini',
 'barziniart',
 'basbanesart',
 'baseart',
 'basebal',
 'baseball',
 'basil',
 'basketball',
 'baskinart',
 'bass',
 'bassart',
 'batchelorart',
 'bateman',
 'batesart',
 'batman',
 'battista',
 'bauschart',
 'bawdenart',
 'baxter',
 'bay',
 'bayart',
 'bayleyart',
 'baynesart',
 'bdsm',
 'bea',
 'bead',
 'beading',
 'beagleart',
 'beahm',
 'beahmart',
 'bear',
 'beard',
 'beardart',
 'beast',
 'beatonart',
 'beatric',
 'beatrix',
 'beatriz',
 'beattie',
 'beattieart',
 'beaumanart',
 'beauti',
 'beauvoir',
 'beauvoirart',
 'beccaria',
 'beck',
 'beckart',
 'becker',
 'beckerart',
 'beckett',
 'beckettart',
 'becki',
 'beech',
 'beechart',
 'beerart',
 'behrendt',
 'beichnerart',
 'belascoart',
 'belgium',
 'bell',
 'bellahsen',
 'bellaire',
 'bellart',
 'bellocart',
 'bellosart',
 'bellow',
 'bellowart',
 'belva',
 'ben',
 'benardeteart',
 'bender',
 'benedict',
 'benge',
 'bengeart',
 'benito',
 'benjamin',
 'bennett',
 'bennettart',
 'benni',
 'bensenart',
 'benson',
 'bensonart',
 'bentleyart',
 'berendtart',
 'berg',
 'bergart',
 'bernadet',
 'bernard',
 'bernd',
 'bernhard',
 'berni',
 'bernic',
 'bernièresart',
 'bernsteinart',
 'berry',
 'bert',
 'beth',
 'betsi',
 'bett',
 'betti',
 'bettina',
 'bettsart',
 'beverley',
 'beverli',
 'bevingtonart',
 'bibl',
 'biblical',
 'bienart',
 'bil',
 'billi',
 'binchyart',
 'biographi',
 'biography',
 'biolog',
 'biology',
 'bird',
 'birdart',
 'birds',
 'birk',
 'birminghamart',
 'birnbaumart',
 'bishop',
 'bishopart',
 'bittman',
 'black',
 'blackburn',
 'blackwellart',
 'blair',
 'blairart',
 'blais',
 'blake',
 'blakeart',
 'blamires',
 'blamiresart',
 'blanca',
 'blanch',
 'blanchardart',
 'blancoart',
 'blaze',
 'blockart',
 'bloom',
 'bloomart',
 'blotnerart',
 'blytonart',
 'bo',
 'board',
 'bob',
 'bobbi',
 'bodanis',
 'bodanisart',
 'bogardart',
 'bogennart',
 'boil',
 'boiled',
 'bois',
 'bonnefoyart',
 'bonni',
 'bonoart',
 'book',
 'bookart',
 'books',
 'booksart',
 'boothart',
 'borchardtart',
 'borges',
 'borgesart',
 'bori',
 'botswana',
 'boulleart',
 'boutsikarisart',
 'bovieart',
 'bowdenart',
 'bowenart',
 'bowerart',
 'bowers',
 'bowersart',
 'bowles',
 'bowlesart',
 'boxcarart',
 'boyd',
 'boydart',
 'br',
 'brad',
 'bradbury',
 'bradburyart',
 'bradfordart',
 'bradi',
 'bradley',
 'bradleyart',
 'brain',
 'bram',
 'brandon',
 'brandsart',
 'brandt',
 'brann',
 'brannart',
 'brantley',
 'brasharesart',
 'braunbeck',
 'braunbeckart',
 'brautiganart',
 'bray',
 'brazil',
 'brenda',
 'brendan',
 'brennan',
 'brennanart',
 'brennertart',
 'brent',
 'brentart',
 'breslinart',
 'bresnahanart',
 'bret',
 'brett',
 'brian',
 'brianart',
 'brickart',
 'bridgesart',
 'bridget',
 'brien',
 'brienart',
 'briggs',
 'briggsart',
 'brindel',
 'brink',
 'british',
 'brock',
 'brockart',
 'brod',
 'brontë',
 'brontëart',
 'brook',
 'brooks',
 'brooksart',
 'brown',
 'brownart',
 'browne',
 'browneart',
 'bruc',
 'bruccoliart',
 'bruce',
 'bruceart',
 'brunkusart',
 'bruno',
 'brunson',
 'bryan',
 'bryce',
 'bryson',
 'brysonart',
 'buchanan',
 'buchananart',
 'buck',
 'buckart',
 'buckby',
 'buddart',
 'buddh',
 'buddhism',
 'buero',
 'buffett',
 'buffettart',
 'buis',
 'buisness',
 'bulgakov',
 'bulgakovart',
 'bullockart',
 'bundesamt',
 'burgess',
 'burgessart',
 'burgin',
 'burianart',
 'burke',
 'burkeart',
 'burnett',
 'burnettart',
 'burnie',
 'burnieart',
 'burnsart',
 'burrart',
 'burroughs',
 'burroughsart',
 'burstenart',
 'burt',
 'burtart',
 'burton',
 'burtonart',
 'bushnell',
 'bushnellart',
 'busi',
 'busiek',
 'business',
 'bussart',
 'butler',
 'butlerart',
 'byattart',
 'byers',
 'byron',
 'cabotart',
 'caldwell',
 'callahanart',
 'calvertart',
 'calvin',
 'calvino',
 'calvinoart',
 'cameron',
 'cameronart',
 'camilla',
 'campbell',
 'campbellart',
 'camus',
 'camusart',
 'canada',
 'canadian',
 'candac',
 'cannon',
 'canon',
 'capote',
 'capoteart',
 'capraart',
 'card',
 'cardart',
 'cardenart',
 'care',
 'carey',
 'careyart',
 'carl',
 'carla',
 'carleart',
 'carlen',
 'carlo',
 'carlson',
 'carlsonart',
 'carmen',
 'carnegie',
 'carnegieart',
 'caro',
 'carol',
 'carolin',
 'carolyn',
 'carpenter',
 'carpenterart',
 'carr',
 'carrart',
 'carratello',
 'carri',
 'carrol',
 'carroll',
 'carrollart',
 'carré',
 'carréart',
 'carson',
 'carsonart',
 'carter',
 'carterart',
 'cartography',
 'cartoon',
 'carusoart',
 'carver',
 'carverart',
 'casey',
 'cashart',
 'cassandra',
 'cassidyart',
 'castanedaart',
 'castart',
 'castle',
 'cat',
 'categori',
 'catharin',
 'catherin',
 'cathi',
 'cathleen',
 'cathol',
 'catholic',
 'catronart',
 'cats',
 'cavanaghart',
 'cecelia',
 'cecil',
 'cecilart',
 'cederholmart',
 'cedr',
 'celest',
 'celia',
 'cent',
 'centuri',
 'century',
 'cervant',
 'cesar',
 'chabon',
 'chabonart',
 'chad',
 'chadwickart',
 'chaim',
 'chalkart',
 'chambersart',
 'chan',
 'chanart',
 'chandler',
 'chandlerart',
 'chang',
 'changart',
 'change',
 'chapman',
 'chapmanart',
 'chapt',
 'charl',
 'charli',
 'charlott',
 'charlton',
 'charrièreart',
 'chaterart',
 'chaucer',
 'chaucerart',
 'che',
 'cheever',
 'cheeverart',
 'chekhov',
 'chemistry',
 'chen',
 'chernowart',
 'cherri',
 'cheryl',
 'chess',
 'chesworthart',
 'chet',
 'cheung',
 'cheungart',
 'chevalier',
 'chevalierart',
 'chick',
 'chie',
 'chiho',
 'child',
 'children',
 'childrens',
 'chiltonart',
 'china',
 'chines',
 'chinua',
 'chomsky',
 'chomskyart',
 'choper',
 'chopin',
 'chopraart',
 'chri',
 'christelowart',
 'christensen',
 'christensenart',
 'christi',
 'christian',
 'christianity',
 'christiansen',
 'christie',
 'christieart',
 'christin',
 'christina',
 'christma',
 'christmas',
 'christoph',
 'christopher',
 'christopherart',
 'chuck',
 'church',
 'cilauro',
 'cindi',
 'ciocchini',
 'cities',
 'civil',
 'cl',
 'clair',
 'clamp',
 'clampart',
 'clancy',
 'clancyart',
 'clar',
 'clara',
 'clare',
 'clarenc',
 'clark',
 'clarkart',
 'clarke',
 'clarkeart',
 'clasonart',
 'class',
 'classic',
 'classics',
 'claud',
 'claudia',
 'clay',
 'clayton',
 'clean',
 'cleary',
 'clearyart',
 'clermontart',
 'clevelandart',
 'cliff',
 'clifford',
 'cliffsnotes',
 'cliffsnotesart',
 'clim',
 'climb',
 'climbing',
 'clint',
 'clinton',
 'clintonart',
 'clive',
 'cloud',
 'club',
 'clyd',
 'clyde',
 'clymer',
 'cobboldart',
 'cod',
 'coding',
 'coelho',
 'coetzee',
 'coetzeeart',
 'cohen',
 'cohenart',
 'cohn',
 'cohnart',
 'colbert',
 'colbertart',
 'cole',
 'coleart',
 'coles',
 'colesart',
 'colett',
 'colferart',
 'colin',
 'collect',
 'collection',
 'collections',
 'colleen',
 'colleg',
 'college',
 'collierart',
 'collins',
 'collinsart',
 'colm',
 'coloni',
 'colson',
 'com',
 'comedi',
 'comedy',
 'comic',
 'comics',
 'comix',
 'commiss',
 'commun',
 'communication',
 'company',
 'companyart',
 'comput',
 'computers',
 'conan',
 'condeart',
 'connell',
 'connellart',
 'conner',
 'conni',
 'connor',
 'connorart',
 'conrad',
 'conradart',
 'conroy',
 'conroyart',
 'conserv',
 'conspiraci',
 'const',
 'contemporari',
 'contemporary',
 'conway',
 'cook',
 'cookart',
 'cookbook',
 'cookbooks',
 'cooking',
 'cooney',
 'cooneyart',
 'cooper',
 'cooperart',
 'copelandart',
 'copleyart',
 'coppola',
 'cordwain',
 'corey',
 'corinn',
 'cormac',
 'cormierart',
 'cornel',
 'cornwell',
 'cornwellart',
 'corporationart',
 'cosby',
 'coshamart',
 'costa',
 'costaart',
 'coulsonart',
 'coulterart',
 'counsel',
 'counselling',
 'count',
 'counting',
 'couplandart',
 'courtenayart',
 'couture',
 'coveyart',
 'cowardart',
 'cowleyart',
 'cox',
 ...]

In [55]:
from sklearn.metrics.pairwise import cosine_similarity

In [56]:
similarity = cosine_similarity(vectors) #similarity matrix

In [57]:
similarity[0]

array([1.        , 0.99127583, 0.95849727, ..., 0.93039761, 0.91964115,
       0.93158776])

In [58]:
def recommend(book):
    book_index = books3[books3['title']== book].index[0]
    distances = similarity[book_index]
    book_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x: x[1])[1:6]
    for i in book_list:
        print(books3.iloc[i[0]].title)

In [59]:
#books3[books3['title']== 'Harry Potter and the Half-Blood Prince'].index[0]

In [60]:
books3[books3.duplicated()]

,bookId,title,tags
4505,4506,Sickened: The True Story of a Lost Childhood,"juli gregoryart,biography,business,children's,..."
4508,4509,Killing Pablo: The Hunt for the World's Great...,"mark bowdenart,biography,business,children's,c..."
4509,4510,Matar a Pablo Escobar/Killing Pablo,"mark bowden,claudio molinariart,biography,busi..."

In [61]:
books3['tags'].value_counts()

randi leffingwellart,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult                                                                                                                                      28
david burnieart,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult                                                                                                                                           26
j.r.r. tolkienart,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,fantasy,classics,fiction,adventure,sci fiction fantasy,fantasy,ep fantasy,literature,fantasy,high fantasy,young adult,novel             20
roger hargreavesart,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult                                                                                                                                       20
gile reedart,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult                                                                                                                                              15
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ..
ian osbornart,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,psychology,nonfiction,health,ment health,self help,science,health                                                                            1
tom toporart,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,mystery,fiction,asian literature,indonesian literature,thriller,novels,thriller,mysteri thriller                                              1
jim powellart,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,history,politics,economics,nonfiction,north american hi...,american history,politics,presidents,literature,american,historical,biographi     1
yuji shiozakiart,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,sequenti art,manga,sequenti art,graph novels,sequenti art,com                                                                             1
daniel p. mannix,katherin dunnart,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,art,biography,business,children's,christian,classics,comics,cookbooks,ebooks,fantasy,fiction,graph novels,histor fiction,history,horror,memoir,music,mystery,nonfiction,poetry,psychology,romance,science,sci fiction,self help,sports,thriller,travel,young adult,nonfiction,history,disability,cultural,biographi                                                                         1
Name: tags, Length: 16552, dtype: int64

In [62]:
books3['title'][9]

'Harry Potter Collection'

In [63]:
recommend("The Ultimate Hitchhiker's Guide to the Galaxy")

The Ultimate Hitchhiker's Guide to the Galaxy
The Ultimate Hitchhiker's Guide
The Ultimate Hitchhiker's Guide to the Galaxy
Hitch-hiker's Guide to the Galaxy: The Original Radio Scripts
The Long Dark Tea-Time of the Soul

In [64]:
books3.iloc[10445].title

'A Farewell to Arms'